export const ru = {
  common: {
    loading: 'Загрузка...',
    error: 'Ошибка',
    success: 'Успешно',
    cancel: 'Отмена',
    confirm: 'Подтвердить',
    save: 'Сохранить',
    delete: 'Удалить',
    edit: 'Редактировать',
    back: 'Назад',
    next: 'Далее',
    previous: 'Назад',
    close: 'Закрыть',
    search: 'Поиск',
    settings: 'Настройки',
    profile: 'Профиль',
    logout: 'Выйти',
    darkMode: 'Темный режим',
    lightMode: 'Светлый режим',
    system: 'Системный',
  },
  tabs: {
    profile: 'Профиль',
    settings: 'Настройки',
    notifications: 'Уведомления',
    features: 'Функции',
    data: 'Данные',
    'cloud-providers': 'Облачные провайдеры',
    'local-providers': 'Локальные провайдеры',
    'service-status': 'Статус сервиса',
    connection: 'Подключение',
    debug: 'Отладка',
    'event-logs': 'Журнал событий',
    update: 'Обновления',
    'task-manager': 'Диспетчер задач',
    'tab-management': 'Управление вкладками',
  },
  tabDescriptions: {
    profile: 'Управление профилем и настройками аккаунта',
    settings: 'Конфигурация параметров приложения',
    notifications: 'Просмотр и управление уведомлениями',
    features: 'Изучение новых и предстоящих функций',
    data: 'Управление данными и хранилищем',
    'cloud-providers': 'Настройка облачных AI-провайдеров и моделей',
    'local-providers': 'Настройка локальных AI-провайдеров и моделей',
    'service-status': 'Мониторинг статуса облачных LLM-сервисов',
    connection: 'Проверка статуса подключения и настроек',
    debug: 'Инструменты отладки и системная информация',
    'event-logs': 'Просмотр системных событий и логов',
    update: 'Проверка обновлений и заметок о выпуске',
    'task-manager': 'Мониторинг системных ресурсов и процессов',
    'tab-management': 'Настройка видимых вкладок и их порядка',
  },
  connection: {
    title: 'Настройки подключения',
    description: 'Управление подключениями к внешним сервисам и интеграциями',
    diagnostics: 'Устранение неполадок',
    hideDiagnostics: 'Скрыть диагностику',
    environmentVariables: 'Переменные окружения',
    envFileHint: 'Вы можете настроить подключения с помощью переменных окружения в файле',
    tokenTypes: 'Типы токенов',
    classicToken: 'classic - Персональный токен доступа с областями',
    fineGrainedToken: 'fine-grained - Токен с доступом к репозиториям и организациям',
    autoConnectHint: 'При установке эти переменные будут использоваться автоматически без необходимости ручного подключения.',
    troubleshootingTip: 'Совет по устранению неполадок',
    troubleshootingSteps: [
      'Проверьте консоль браузера на наличие ошибок',
      'Убедитесь, что ваши токены имеют правильные разрешения',
      'Попробуйте очистить кеш и куки браузера',
      'Убедитесь, что ваш браузер разрешает сторонние куки при использовании интеграций',
    ],
  },
  data: {
    chats: 'Чаты',
    exportAll: 'Экспорт всех чатов',
    exportAllDescription: 'Экспорт всех ваших чатов в JSON-файл',
    exportSelected: 'Экспорт выбранных чатов',
    exportSelectedDescription: 'Экспорт выбранных чатов в JSON-файл',
    deleteAll: 'Удалить все чаты',
    deleteAllDescription: 'Удалить всю историю чатов',
    settings: 'Настройки',
    exportSettings: 'Экспорт всех настроек',
    exportSettingsDescription: 'Экспорт всех ваших настроек в JSON-файл',
    resetSettings: 'Сбросить все настройки',
    resetSettingsDescription: 'Сбросить все настройки к значениям по умолчанию',
    apiKeys: 'API Ключи',
    downloadTemplate: 'Скачать шаблон',
    downloadTemplateDescription: 'Скачать шаблонный файл для ваших API ключей',
    importKeys: 'Импорт API ключей',
    importKeysDescription: 'Импорт API ключей из JSON-файла',
    dataUsage: 'Использование данных',
    noChats: 'Нет чатов для экспорта',
    exporting: 'Экспорт...',
    deleting: 'Удаление...',
    resetting: 'Сброс...',
  },
  debug: {
    errors: 'Ошибки',
    noErrors: 'Ошибок не обнаружено',
    errorsFound: 'Обнаружены ошибки',
    ollamaService: 'Сервис Ollama',
    ollamaStatus: {
      running: 'Запущен',
      notRunning: 'Не запущен',
      disabled: 'Отключено',
    },
    refreshSystemInfo: 'Обновить системную информацию',
    systemInfo: 'Системная информация',
    os: 'ОС',
    platform: 'Платформа',
    arch: 'Архитектура',
    nodeVersion: 'Версия Node',
    chromeVersion: 'Версия Chrome',
    electronVersion: 'Версия Electron',
    memoryUsage: 'Использование памяти',
    cpuUsage: 'Использование CPU',
    uptime: 'Время работы',
    exportFormats: {
      json: 'Экспорт в JSON',
      csv: 'Экспорт в CSV',
      pdf: 'Экспорт в PDF',
      txt: 'Экспорт в текст',
    },
  },
  features: {
    coreFeatures: 'Основные функции',
    coreDescription: 'Основные функции, включенные по умолчанию для оптимальной работы',
    betaFeatures: 'Бета-функции',
    betaDescription: 'Новые функции, готовые к тестированию, но могут иметь некоторые проблемы',
    promptLibrary: 'Библиотека подсказок',
    promptLibraryDescription: 'Выберите подсказку из библиотеки для использования в качестве системной подсказки',
    latestBranch: 'Обновления из основной ветки',
    latestBranchDescription: 'Получайте последние обновления из основной ветки разработки',
    autoSelectTemplate: 'Автоматический выбор шаблона',
    autoSelectTemplateDescription: 'Автоматически выбирать стартовый шаблон',
    contextOptimization: 'Оптимизация контекста',
    contextOptimizationDescription: 'Оптимизировать контекст для лучших ответов',
    eventLogs: 'Логи событий',
    eventLogsDescription: 'Включить детальное логирование событий и истории',
    enabled: 'включено',
    disabled: 'отключено',
    updated: 'обновлено',
  },
  beta: {
    label: 'БЕТА',
    tooltip: 'Бета-функция - может содержать ошибки',
  },
  experimental: {
    label: 'ЭКСПЕРИМЕНТАЛЬНО',
    tooltip: 'Экспериментальная функция - используйте с осторожностью',
  },
};
